services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    networks:
      - app_network

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=devopsdojo
      - POSTGRES_PASSWORD=Pssw0rd
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    networks:
      - app_network
    depends_on:
      - postgres

  adminer:
    image: adminer
    restart: always
    networks:
      - app_network

  proxy-manager:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres:
    driver: local
